config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "oauth" }
  get "pages/index"
  resources :dashboard, only: [:show]
  post "/toggle_webhook", to: "webhook#toggle_pull_request_webhook"
  post "/handle_pull_request", to: "webhook#handle_pull_request"
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repo.rb
class Repo < ApplicationRecord
  belongs_to :user

  validates :full_name, presence: true
  validates :name, presence: true
  validates :active, inclusion: { in: [true, false] }

  scope :ordered_by_active, -> { order("active desc") }

  def toggle_active
    update_attributes(active: !active?)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :repos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:github]

  validates :username, presence: true
  validates :first_name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.nickname
      user.first_name = auth.info.name
      user.github_access_token = auth.credentials.token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  private

  def after_sign_in_path_for(resource)
    dashboard_path(resource.id)
  end

  def after_sign_out_path_for(_resource)
    root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
    @repos = @user.repos.ordered_by_active
  end
end

app/controllers/oauth_controller.rb
require "github_client"

class OauthController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      GithubClient.new(@user, Octokit::Client.new).populate_user_repos
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(
        :notice,
        :success,
        kind: "Github",
      ) if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/controllers/webhook_controller.rb
require "github_client"
require "pull_request"

class WebhookController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:handle_pull_request]
  skip_before_action :authenticate_user!, only: [:handle_pull_request]

  def toggle_pull_request_webhook
    repo = Repo.find(params[:repo])
    user = repo.user
    GithubClient.new(nil, Octokit::Client.new(
                            access_token: user.github_access_token,
    )).toggle_webhook(repo)
  end

  def handle_pull_request
    if params["pull_request"]
      BuildJob.new(PullRequest.build_data(params)).delay.perform
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<section class="repos">
  <div class="welcome-message">
    <%= "Welcome, #{@user.first_name}!" %>
  </div>
  <div class="repo-list-div">
    <ul class="repo-list">
      <% @repos.each do |repo| %>
        <%= link_to toggle_webhook_path(repo: repo), remote: true, method: :post do %>
          <li class="repo <%= repo.active? ? 'active' : '' %>">
            <span class="repo-name"><%= repo.name %></span>
            <p class="repo-status"><%= repo.active? ? 'ON!' : 'TURN CI ON?' %></p>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JackCi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<section id="header">
  <div class="header-info">
    <h1 class="header-text">Test and Deploy with Confidence!</h1>
    <h3 class="header-description">Easily sync your GitHub projects with Jack CI and you’ll be testing your code in minutes!</h3>
  </div>
</section>

app/views/pages/index.html.erb
<%= render partial: "header" %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">JackCI</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Blog</a></li>
        <li><a href="#">Status</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to user_github_omniauth_authorize_path, class: "o-auth btn btn-success navbar-btn" do %>
              <i class="fa fa-github"><span class="button-text">Sign In With Github</span></i>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>